<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class ActualizacionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => 1,
                'nombre' => 'Malcolm',
                'surname' => 'Cordova',
                'especialidad' => 'Cirugía Buco-maxilofacial',
                'universidad' => 'prueba',
                'ano' => '200',
                'org' => 'SVCBMF',
                'website' => 'prueba',
                'email' => 'mercadocreativo@gmail.com',
                'direccion' => 'caracas',
                'direccion1' => 'caracas',
                'estado' => 'Distrito Federal',
                'ciudad' => 'caracas',
                'telefonos' => '04241874370',
                'tel1' => '04241874370',
                'telhome' => '04241874370',
                'telmovil' => '04241874370',
                'telprincipal' => '04241874370',
                'facebook' => 'prueba',
                'instagram' => 'prueba',
                'twitter' => 'prueba',
                'linkedin' => 'prueba',
                'created_at' => Carbon::parse('2024-04-29 21:36:25'),
                'updated_at' => Carbon::parse('2024-04-29 21:36:25'),
            ],
            [
                'id' => 2,
                'nombre' => 'Maria Jose',
                'surname' => 'Perezo Moron',
                'especialidad' => 'Cirugía Bucal',
                'universidad' => 'Universidad del Zulia',
                'ano' => null,
                'org' => 'SVCBMF',
                'website' => null,
                'email' => 'mariajoseperozom@gmail.com',
                'direccion' => 'Calle 78 con 13a. Centro Profesional Jimero Jimenez',
                'direccion1' => null,
                'estado' => 'Zulia',
                'ciudad' => 'Maracaibo',
                'telefonos' => null,
                'tel1' => null,
                'telhome' => null,
                'telmovil' => '04127558816',
                'telprincipal' => '04248251408',
                'facebook' => null,
                'instagram' => '@dra.mariajoperozo',
                'twitter' => null,
                'linkedin' => null,
                'created_at' => Carbon::parse('2024-05-09 18:35:01'),
                'updated_at' => Carbon::parse('2024-05-09 18:35:01'),
            ],
            [
                'id' => 3,
                'nombre' => 'Iliana Carolina',
                'surname' => 'Gonzalez Mendoza',
                'especialidad' => 'Cirugía Buco-maxilofacial',
                'universidad' => 'Hospital general del Oeste los Magallanes de Catia',
                'ano' => null,
                'org' => 'SVCBMF',
                'website' => null,
                'email' => 'od.ilianagonzalez@gmail.com',
                'direccion' => 'Torre inpreabogado, PB Consultorio D&A, Av. la salle Plaza Venezuela',
                'direccion1' => null,
                'estado' => 'Distrito Capital',
                'ciudad' => 'Caracas',
                'telefonos' => null,
                'tel1' => null,
                'telhome' => null,
                'telmovil' => null,
                'telprincipal' => '04242039428',
                'facebook' => 'Dra iliana González Maxilofacial',
                'instagram' => '@drailianamaxilo',
                'twitter' => null,
                'linkedin' => null,
                'created_at' => Carbon::parse('2024-05-09 18:43:04'),
                'updated_at' => Carbon::parse('2024-05-09 18:43:04'),
            ],
            [
                'id' => 4,
                'nombre' => 'Gustavo Alfonzo',
                'surname' => 'Bustamante Lopez',
                'especialidad' => 'Cirugía Bucal',
                'universidad' => 'Universidad del Zulia',
                'ano' => null,
                'org' => 'SVCBMF',
                'website' => null,
                'email' => 'tavo238@hotmail.com',
                'direccion' => 'Nueva clínica D\'Empaire Av. Fuerzas armadas Piso 1 Consultorio 14',
                'direccion1' => null,
                'estado' => 'Zulia',
                'ciudad' => 'Maracaibo',
                'telefonos' => null,
                'tel1' => null,
                'telhome' => null,
                'telmovil' => null,
                'telprincipal' => '04146483642',
                'facebook' => null,
                'instagram' => null,
                'twitter' => null,
                'linkedin' => '@cirugiabucal',
                'created_at' => Carbon::parse('2024-05-09 18:47:11'),
                'updated_at' => Carbon::parse('2024-05-09 18:47:11'),
            ],
            [
                'id' => 5,
                'nombre' => 'Gerardo Ramon',
                'surname' => 'Vitale Sanchez',
                'especialidad' => 'Cirugía Buco-maxilofacial',
                'universidad' => 'Ciudad Hospitalaria Enrique Tejera',
                'ano' => null,
                'org' => 'SVCBMF',
                'website' => null,
                'email' => 'drgerardovitale@gmail.com',
                'direccion' => 'Torre la Arboleda Av. Las delicias Piso 2 Oficina 2-3 Maracay Estado Aragua',
                'direccion1' => null,
                'estado' => 'Aragua',
                'ciudad' => 'Maracay',
                'telefonos' => null,
                'tel1' => null,
                'telhome' => null,
                'telmovil' => null,
                'telprincipal' => '04125009899',
                'facebook' => 'Dr. Gerardo Vitale- cirujano maxilofacial',
                'instagram' => '@dr_vitale.maxilofacial',
                'twitter' => null,
                'linkedin' => null,
                'created_at' => Carbon::parse('2024-05-09 18:54:26'),
                'updated_at' => Carbon::parse('2024-05-09 18:54:26'),
            ],
            [
                'id' => 6,
                'nombre' => 'Hemil Dario',
                'surname' => 'Rosales Molina',
                'especialidad' => 'Cirugía Buco-maxilofacial',
                'universidad' => 'Hospital General del Oeste',
                'ano' => null,
                'org' => 'SVCBMF',
                'website' => null,
                'email' => 'drhemilrosales@gmail.com',
                'direccion' => 'Centro Profesional Santa Paula, Torre B piso 11 Oficina 1107 Avenido Circunvalación del sol santa Paula',
                'direccion1' => null,
                'estado' => 'Miranda',
                'ciudad' => 'Caracas',
                'telefonos' => null,
                'tel1' => null,
                'telhome' => null,
                'telmovil' => '04149203623',
                'telprincipal' => '04123161039',
                'facebook' => null,
                'instagram' => '@dr.rosales',
                'twitter' => null,
                'linkedin' => null,
                'created_at' => Carbon::parse('2024-05-09 19:02:10'),
                'updated_at' => Carbon::parse('2024-05-09 19:02:10'),
            ],
            [
                'id' => 7,
                'nombre' => 'Salomon',
                'surname' => 'Ramos Matheus',
                'especialidad' => 'Cirugía Bucal',
                'universidad' => 'Universidad del Zulia',
                'ano' => null,
                'org' => 'SVCBMF',
                'website' => null,
                'email' => 'Salomon_ramos@hotmail.com',
                'direccion' => 'Centro Clínico Aries. Maracaibo',
                'direccion1' => null,
                'estado' => 'Zulia',
                'ciudad' => 'Maracaibo',
                'telefonos' => null,
                'tel1' => null,
                'telhome' => null,
                'telmovil' => null,
                'telprincipal' => '04121213952',
                'facebook' => null,
                'instagram' => '@od.salomonramos',
                'twitter' => null,
                'linkedin' => null,
                'created_at' => Carbon::parse('2024-05-09 19:07:33'),
                'updated_at' => Carbon::parse('2024-05-09 19:07:33'),
            ],
            [
                'id' => 8,
                'nombre' => 'Alberto Jose',
                'surname' => 'Gonzalez Sanchez',
                'especialidad' => 'Cirugía Buco-maxilofacial',
                'universidad' => 'Universidad del Zulia',
                'ano' => null,
                'org' => 'SVCBMF',
                'website' => null,
                'email' => 'albertogonzalezcirujano@gmail.com',
                'direccion' => 'Calle Quebrada Honda Clínica San Pablo Piso 1 Carúpano Edo. Sucre',
                'direccion1' => null,
                'estado' => 'Sucre',
                'ciudad' => null,
                'telefonos' => null,
                'tel1' => null,
                'telhome' => null,
                'telmovil' => '04248080781',
                'telprincipal' => '04121844101',
                'facebook' => null,
                'instagram' => '@albertojgs12',
                'twitter' => null,
                'linkedin' => null,
                'created_at' => Carbon::parse('2024-05-09 19:26:05'),
                'updated_at' => Carbon::parse('2024-05-09 19:26:05'),
            ],
            [
                'id' => 9,
                'nombre' => 'Salomon Ramos',
                'surname' => 'Matheus',
                'especialidad' => 'Cirugía Bucal',
                'universidad' => 'Universidad del Zulia',
                'ano' => null,
                'org' => 'SVCBMF',
                'website' => null,
                'email' => 'salomon_ramos@hotmail.com',
                'direccion' => 'Centro Clínico Aries. Maracaibo estado Zulia',
                'direccion1' => null,
                'estado' => 'Zulia',
                'ciudad' => 'Maracaibo',
                'telefonos' => null,
                'tel1' => null,
                'telhome' => null,
                'telmovil' => null,
                'telprincipal' => '04121213952',
                'facebook' => null,
                'instagram' => '@od.salomonramos',
                'twitter' => null,
                'linkedin' => null,
                'created_at' => Carbon::parse('2024-05-15 20:40:44'),
                'updated_at' => Carbon::parse('2024-05-15 20:40:44'),
            ],
            [
                'id' => 10,
                'nombre' => 'Arianny Daniela',
                'surname' => 'Peraza Serradas',
                'especialidad' => 'Cirugía Bucal',
                'universidad' => 'Universidad del Zulia',
                'ano' => null,
                'org' => 'SVCBMF',
                'website' => null,
                'email' => 'ariannyperazas@gmail.com',
                'direccion' => 'Av 3Y entre calle 70 y 71 Edif. Las amelias PB.Clínica Dental Innova Diagonal a la residencia oficial del gobernador.',
                'direccion1' => null,
                'estado' => 'Zulia',
                'ciudad' => 'Maracaibo',
                'telefonos' => null,
                'tel1' => null,
                'telhome' => '04165018787',
                'telmovil' => '04126636775',
                'telprincipal' => null,
                'facebook' => '@dra.ariperaza',
                'instagram' => null,
                'twitter' => null,
                'linkedin' => null,
                'created_at' => Carbon::parse('2024-05-15 20:51:37'),
                'updated_at' => Carbon::parse('2024-05-15 20:51:37'),
            ],
            [
                'id' => 11,
                'nombre' => 'Arianny Daniela',
                'surname' => 'Peraza Serradas',
                'especialidad' => 'Cirugía Bucal',
                'universidad' => 'Universidad del Zulia',
                'ano' => null,
                'org' => 'SVCBMF',
                'website' => null,
                'email' => 'ariannyperazas@gmail.com',
                'direccion' => 'Av 3Y entre calle 70 y 71 Edif. Las amelias PB.Clínica Dental Innova Diagonal a la residencia oficial del gobernador.',
                'direccion1' => null,
                'estado' => 'Zulia',
                'ciudad' => 'Maracaibo',
                'telefonos' => null,
                'tel1' => null,
                'telhome' => null,
                'telmovil' => '04165018787',
                'telprincipal' => '04126636775',
                'facebook' => null,
                'instagram' => null,
                'twitter' => null,
                'linkedin' => null,
                'created_at' => Carbon::parse('2024-05-15 21:09:28'),
                'updated_at' => Carbon::parse('2024-05-15 21:09:28'),
            ],
            [
                'id' => 12,
                'nombre' => 'Salvador Jose',
                'surname' => 'Ollalve Bove',
                'especialidad' => 'Cirugía Buco-maxilofacial',
                'universidad' => 'Ciudad Hospitalaria Enrique Tejera',
                'ano' => null,
                'org' => 'SVCBMF',
                'website' => null,
                'email' => 'salvadorrollalve@gmail.com',
                'direccion' => "CEO R lorven - Puerto Cabello \nDental studio LP - Puerto Cabello \nCentro Clinico San Jose - Puerto Cabello",
                'direccion1' => null,
                'estado' => null,
                'ciudad' => null,
                'telefonos' => null,
                'tel1' => null,
                'telhome' => null,
                'telmovil' => null,
                'telprincipal' => '04121771147',
                'facebook' => null,
                'instagram' => '@salvadorollalvebove',
                'twitter' => null,
                'linkedin' => null,
                'created_at' => Carbon::parse('2024-05-15 21:18:54'),
                'updated_at' => Carbon::parse('2024-05-15 21:18:54'),
            ],
            [
                'id' => 13,
                'nombre' => 'Luisangela Maria',
                'surname' => 'Castillo Bruzual',
                'especialidad' => 'Cirugía Buco-maxilofacial',
                'universidad' => 'Ciudad Hospitalaria Enrique Tejera',
                'ano' => null,
                'org' => 'SVCBMF',
                'website' => null,
                'email' => 'luisangela.lc@gmail.com',
                'direccion' => 'Caracas  CCCT - Cojedes CC Villa Center',
                'direccion1' => null,
                'estado' => 'Miranda',
                'ciudad' => 'Caracas',
                'telefonos' => null,
                'tel1' => null,
                'telhome' => null,
                'telmovil' => null,
                'telprincipal' => '04121436923',
                'facebook' => null,
                'instagram' => '@dracastillob',
                'twitter' => null,
                'linkedin' => null,
                'created_at' => Carbon::parse('2024-05-16 19:42:45'),
                'updated_at' => Carbon::parse('2024-05-16 19:42:45'),
            ],
            [
                'id' => 14,
                'nombre' => 'Ana Carolina',
                'surname' => 'Villarroel Sole',
                'especialidad' => 'Cirugía Bucal',
                'universidad' => 'Universidad del Zulia',
                'ano' => null,
                'org' => 'SVCBMF',
                'website' => null,
                'email' => 'dra.anavillarroel@gmail.com',
                'direccion' => 'Carre21-A entre calle 54 y 55. Centro Clinico Quirurgico CARALI 2 Planta Baja Barquisimeto',
                'direccion1' => null,
                'estado' => 'Lara',
                'ciudad' => 'Barquisimeto',
                'telefonos' => null,
                'tel1' => null,
                'telhome' => '04149521113',
                'telmovil' => '04128516095',
                'telprincipal' => 'Dra.Ana Villarroel',
                'facebook' => 'dra.anavillaroel',
                'instagram' => null,
                'twitter' => null,
                'linkedin' => null,
                'created_at' => Carbon::parse('2024-05-16 19:48:43'),
                'updated_at' => Carbon::parse('2024-05-16 19:48:43'),
            ],
            [
                'id' => 15,
                'nombre' => 'Domingo A',
                'surname' => 'Malave Farina',
                'especialidad' => 'Cirugía Buco-maxilofacial',
                'universidad' => 'Universidad de Pittsburgh PA USA',
                'ano' => null,
                'org' => 'SVCBMF',
                'website' => null,
                'email' => 'domingomalavef@gmail.com',
                'direccion' => "Instituto Docente de Urología, Final AV Carabobo Urb. La viña consultorio 514 Piso 5 \nEdo. Carabobo \nC.P.V Clínica la Viña \nCruz Roja Valencia",
                'direccion1' => null,
                'estado' => 'Carabobo',
                'ciudad' => 'Valencia',
                'telefonos' => null,
                'tel1' => null,
                'telhome' => null,
                'telmovil' => '04244417769',
                'telprincipal' => '04144283282',
                'facebook' => null,
                'instagram' => null,
                'twitter' => null,
                'linkedin' => null,
                'created_at' => Carbon::parse('2024-05-16 19:54:26'),
                'updated_at' => Carbon::parse('2024-05-16 19:54:26'),
            ],
            [
                'id' => 16,
                'nombre' => 'Carlos',
                'surname' => 'Manresa Bruguera',
                'especialidad' => 'Cirugía Buco-maxilofacial',
                'universidad' => 'Universidad Gran Mariscal de Ayacucho',
                'ano' => null,
                'org' => 'SVCBMF',
                'website' => null,
                'email' => 'manresa723@gmail.com',
                'direccion' => 'Av. La Estancia, CCCT Torre D piso 2, oficina 226 Grupo Hera-Centro de Cabeza y Cuello Caracas',
                'direccion1' => null,
                'estado' => 'Miranda',
                'ciudad' => 'Caracas',
                'telefonos' => null,
                'tel1' => null,
                'telhome' => null,
                'telmovil' => null,
                'telprincipal' => '04140338943',
                'facebook' => null,
                'instagram' => '@Carlosmanresab',
                'twitter' => null,
                'linkedin' => null,
                'created_at' => Carbon::parse('2024-05-30 20:54:43'),
                'updated_at' => Carbon::parse('2024-05-30 20:54:43'),
            ],
            [
                'id' => 17,
                'nombre' => 'Miguel Antonio',
                'surname' => 'Mavarez Reyes',
                'especialidad' => 'Cirugía Buco-maxilofacial',
                'universidad' => 'Hospital Dr. Adolfo Prince Lara',
                'ano' => null,
                'org' => 'SVCBMF',
                'website' => null,
                'email' => 'maxilomavarez@gmail.com',
                'direccion' => 'Consultorio Odontológico y Maxilofacial  San Antonio Calle Ayacucho entre Calle Vargas y Democracia',
                'direccion1' => null,
                'estado' => null,
                'ciudad' => null,
                'telefonos' => null,
                'tel1' => null,
                'telhome' => null,
                'telmovil' => '04244628083',
                'telprincipal' => null,
                'facebook' => null,
                'instagram' => '@maxilomavarez',
                'twitter' => null,
                'linkedin' => null,
                'created_at' => Carbon::parse('2024-05-30 21:10:56'),
                'updated_at' => Carbon::parse('2024-05-30 21:10:56'),
            ],
            [
                'id' => 18,
                'nombre' => 'Test',
                'surname' => 'Test',
                'especialidad' => 'Cirugía Buco-maxilofacial',
                'universidad' => 'Test',
                'ano' => 'Test',
                'org' => 'SVCBMF',
                'website' => 'Test',
                'email' => 'Test@Test.com',
                'direccion' => 'Test',
                'direccion1' => null,
                'estado' => null,
                'ciudad' => null,
                'telefonos' => null,
                'tel1' => null,
                'telhome' => null,
                'telmovil' => null,
                'telprincipal' => '123456',
                'facebook' => null,
                'instagram' => null,
                'twitter' => null,
                'linkedin' => null,
                'created_at' => Carbon::parse('2025-05-25 01:35:39'),
                'updated_at' => Carbon::parse('2025-05-25 01:35:39'),
            ],
            [
                'id' => 19,
                'nombre' => 'Malcolm',
                'surname' => 'Cordova',
                'especialidad' => 'Cirugía Buco-maxilofacial',
                'universidad' => '3223',
                'ano' => null,
                'org' => 'SVCBMF',
                'website' => null,
                'email' => 'mercadocreativo@gmail.com',
                'direccion' => 'caracas',
                'direccion1' => 'caracas',
                'estado' => 'Distrito Federal',
                'ciudad' => 'caracas',
                'telefonos' => '04241874370',
                'tel1' => null,
                'telhome' => null,
                'telmovil' => null,
                'telprincipal' => '04241874370',
                'facebook' => null,
                'instagram' => null,
                'twitter' => null,
                'linkedin' => null,
                'created_at' => Carbon::parse('2025-05-26 00:20:18'),
                'updated_at' => Carbon::parse('2025-05-26 00:20:18'),
            ],
        ];

        DB::table('actualizacions')->insert($data);
    }
}
