<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class AfiliacionesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => 1,
               
                'nombres' => 'Pedro José ',
                'apellidos' => 'Jiménez Lucena',
                'titulo' => 'Especialista en Cirugía Bucal y Maxilofacial',
                'universidad' => 'Universidad de Carabobo',
                'graduacion' => '2017',
                'ciudad' => 'Maracay',
                'estado' => 'Aragua',
                'telefonos' => '0414.470.24.94',
                'email' => 'pedrojjimenezl@gmail.com',
                'archivo' => 'Requisitos-para-optar-a-ser-Miembro-de-la-SVCBMF0001.pdf',
                'created_at' => Carbon::parse('2019-12-19 22:14:05'),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 2,
               
                'nombres' => 'Elena Victoria',
                'apellidos' => 'Mujica Molleja',
                'titulo' => 'Cirugia Bucal ',
                'universidad' => 'Universidad Central de Venezuela',
                'graduacion' => '2013',
                'ciudad' => 'caracas',
                'estado' => 'dtto Capital ',
                'telefonos' => '02126053793',
                'email' => 'elenavmm8@gmail.com',
                'archivo' => 'RECAUDOS-SVCBM.pdf',
                'created_at' => Carbon::parse('2019-12-19 22:14:05'),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 3,
               
                'nombres' => 'Ksenia ',
                'apellidos' => 'Basov Jakovlev',
                'titulo' => 'Especialista en cirugía bucal y maxilofacial',
                'universidad' => 'Carabobo',
                'graduacion' => '2017',
                'ciudad' => 'Valencia',
                'estado' => 'Carabobo',
                'telefonos' => '4144793197',
                'email' => 'kisabas@gmail.com',
                'archivo' => 'sociedad-venezolana.pdf',
                'created_at' => Carbon::parse('2019-12-19 22:14:05'),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 4,
               
                'nombres' => 'Efraín José',
                'apellidos' => 'García A. Gonílez',
                'titulo' => 'CIRUJANO BUCAL Y MAXILOFACIAL',
                'universidad' => 'UNIVERSIDAD DE CARABOBO',
                'graduacion' => '2017',
                'ciudad' => 'VALENCIA',
                'estado' => 'CARABOBO',
                'telefonos' => '04143463027',
                'email' => 'OD.EFRAIN.GARCIA@HOTMAIL.COM',
                'archivo' => 'SINTESIS-CURRICULAR-1-hoja.pdf',
                'created_at' => Carbon::parse('2019-12-19 22:14:05'),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 5,
               
                'nombres' => 'Efraín José',
                'apellidos' => 'García A. Gonílez',
                'titulo' => 'CIRUJANO BUCAL Y MAXILOFACIAL',
                'universidad' => 'UNIVERSIDAD DE CARABOBO',
                'graduacion' => '2017',
                'ciudad' => 'VALENCIA',
                'estado' => 'CARABOBO',
                'telefonos' => '04143463027',
                'email' => 'OD.EFRAIN.GARCIA@HOTMAIL.COM',
                'archivo' => 'RECAUDOS-DR-EFRAIN GARCIA.pdf',
                'created_at' => Carbon::parse('2019-12-19 22:14:05'),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 7,
               
                'nombres' => 'nelcar rafael',
                'apellidos' => 'zerpa adrian',
                'titulo' => 'cirujano bucal y maxilofacial',
                'universidad' => 'universidad de carabobo',
                'graduacion' => '2016',
                'ciudad' => 'valencia',
                'estado' => 'carabobo',
                'telefonos' => '4249156049',
                'email' => 'nelcarz84@gmail.com',
                'archivo' => 'resumen-Curricular-nelcar-zerpa-1-pagina.pdf',
                'created_at' => Carbon::parse('2019-12-19 22:14:05'),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 8,
               
                'nombres' => 'Jorge luis',
                'apellidos' => 'Borges Asuaje',
                'titulo' => 'Cirugía Bucal y Maxilofacial',
                'universidad' => 'Ciudad Hospitalaria Dr. Enrique Tejera. ',
                'graduacion' => '2016',
                'ciudad' => 'Valencia',
                'estado' => 'Carabobo',
                'telefonos' => '4144164803',
                'email' => 'jorgelborgesa@gmail.com',
                'archivo' => 'requisitos-para-la-sociedad.pdf',
                'created_at' => Carbon::parse('2019-12-19 22:14:05'),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 9,
               
                'nombres' => 'ROXELYN MERCEDES',
                'apellidos' => 'CRISTALINO ROJANO',
                'titulo' => 'ODONTOLOGO CIRUJANO BUCOMAXILOFACIAL',
                'universidad' => 'IVSS HOSPITAL DR DOMINGO LUCIANI',
                'graduacion' => '2018',
                'ciudad' => 'CARACAS',
                'estado' => 'MIRANDA',
                'telefonos' => '04246277417',
                'email' => 'od.roxelyncristalino@hotmail.com',
                'archivo' => 'DOCUMENTOS-PARA-LA-SOCIEDAD-2018.pdf',
                'created_at' => Carbon::parse('2019-12-19 22:14:05'),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 10,
               
                'nombres' => 'JORGE',
                'apellidos' => 'BORGES',
                'titulo' => 'Cirugía Bucal y Maxilofacial',
                'universidad' => 'Ciudad Hospitalaria Dr. Enrique Tejera. ',
                'graduacion' => '2016',
                'ciudad' => 'Valencia',
                'estado' => 'Carabobo',
                'telefonos' => '4144164803',
                'email' => 'jorgelborgesa@gmail.com',
                'archivo' => 'requisitos-para-la-sociedad.pdf',
                'created_at' => Carbon::parse('2019-12-19 22:14:05'),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 11,
               
                'nombres' => 'Anllert Irais',
                'apellidos' => 'Ruiz Rangel',
                'titulo' => 'Odontóloga',
                'universidad' => 'UNERG',
                'graduacion' => '2012',
                'ciudad' => 'Caracas',
                'estado' => 'Miranda',
                'telefonos' => '04249142014',
                'email' => 'anllert.11@gmail.com',
                'archivo' => 'miembroadherente-ANLLERT-RUIZ.pdf',
                'created_at' => Carbon::parse('2019-12-19 22:14:05'),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 12,
               
                'nombres' => 'Laura Angelica',
                'apellidos' => 'RamÃ­rez Alarcon',
                'titulo' => 'Cirujano Bucal ',
                'universidad' => 'La Universidad del Zulia',
                'graduacion' => '2017',
                'ciudad' => 'Maracaibo',
                'estado' => 'Zulia',
                'telefonos' => '0254.5610761/0416.1625640',
                'email' => 'lauraangelicaramirezalarcon@gmail.com',
                'archivo' => 'Titulo-Laura-Especialista.pdf',
                'created_at' => Carbon::parse('2019-12-19 22:14:05'),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 13,
               
                'nombres' => 'Liseth Nathalie',
                'apellidos' => 'Chacón Alvarez',
                'titulo' => 'Odontólogo',
                'universidad' => 'Universidad Santa Maria',
                'graduacion' => '2017',
                'ciudad' => 'Gran Caracas',
                'estado' => 'Miranda',
                'telefonos' => '0414.759.59.16',
                'email' => 'liseth.chacon30@gmail.com',
                'archivo' => 'Curriculum-actualizado-el-22-4-Resumen.pdf',
                'created_at' => Carbon::parse('2019-12-19 22:14:05'),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 14,
               
                'nombres' => 'Rossana Verónica',
                'apellidos' => 'Rosas Nieves',
                'titulo' => 'Odontología',
                'universidad' => 'Universidad Central de Venezuela',
                'graduacion' => '2016',
                'ciudad' => 'Caracas',
                'estado' => 'Caracas',
                'telefonos' => '04264860166',
                'email' => 'odrossanarosas@hotmail.com',
                'archivo' => 'titulo-rossana-odontologia.pdf',
                'created_at' => Carbon::parse('2019-12-19 22:14:05'),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 15,
               
                'nombres' => 'Rossana Verónica',
                'apellidos' => 'Rosas Nieves',
                'titulo' => 'Odontología',
                'universidad' => 'Universidad Central de Venezuela',
                'graduacion' => '2016',
                'ciudad' => 'Caracas',
                'estado' => 'Caracas',
                'telefonos' => '04264860166',
                'email' => 'odrossanarosas@hotmail.com',
                'archivo' => 'Documento.pdf',
                'created_at' => Carbon::parse('2019-12-19 22:14:05'),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 16,
               
                'nombres' => 'Braulio Heriberto',
                'apellidos' => 'López Arévalo',
                'titulo' => 'Especialista en Cirugía Bucal y Maxilofacial',
                'universidad' => 'Universidad de Carabobo',
                'graduacion' => '2017',
                'ciudad' => 'Valencia',
                'estado' => 'Carabobo',
                'telefonos' => '04144169994',
                'email' => 'bhlabs7@gmail.com',
                'archivo' => 'Recaudos-afiliacion-SVCBMF-Braulio-Lopez.pdf',
                'created_at' => Carbon::parse('2019-12-19 22:14:05'),
                'updated_at' => null,
                'deleted_at' => null,
            ],
        ];

        DB::table('afiliaciones')->insert($data);
    }
}
